var annotated =
[
    [ "AllexandreStrategy", "class_allexandre_strategy.html", "class_allexandre_strategy" ],
    [ "AtrialMachine2d", "class_atrial_machine2d.html", "class_atrial_machine2d" ],
    [ "atrialParameters", "classatrial_parameters.html", "classatrial_parameters" ],
    [ "burster", "classburster.html", "classburster" ],
    [ "CardiacMesh", "class_cardiac_mesh.html", "class_cardiac_mesh" ],
    [ "CartesianGrid", "class_cartesian_grid.html", "class_cartesian_grid" ],
    [ "CCamera", "class_c_camera.html", "class_c_camera" ],
    [ "compare_TimestepNode", "structcompare___timestep_node.html", "structcompare___timestep_node" ],
    [ "CurveData", "class_curve_data.html", "class_curve_data" ],
    [ "DefaultPlot", "class_default_plot.html", "class_default_plot" ],
    [ "DiffusionMatrix", "class_diffusion_matrix.html", "class_diffusion_matrix" ],
    [ "DiffusionPainter", "class_diffusion_painter.html", "class_diffusion_painter" ],
    [ "FitzHughNagumo", "class_fitz_hugh_nagumo.html", "class_fitz_hugh_nagumo" ],
    [ "ForwardEulerStrategy", "class_forward_euler_strategy.html", "class_forward_euler_strategy" ],
    [ "glAtrium", "classgl_atrium.html", "classgl_atrium" ],
    [ "ioHandler", "classio_handler.html", "classio_handler" ],
    [ "Node", "class_node.html", "class_node" ],
    [ "NumericStrategy", "class_numeric_strategy.html", "class_numeric_strategy" ],
    [ "Oscillator", "class_oscillator.html", "class_oscillator" ],
    [ "oscillatorToTimestepHandle", "structoscillator_to_timestep_handle.html", "structoscillator_to_timestep_handle" ],
    [ "oscillatorToUpdateNode", "structoscillator_to_update_node.html", "structoscillator_to_update_node" ],
    [ "Pix", "class_pix.html", "class_pix" ],
    [ "Probe", "class_probe.html", "class_probe" ],
    [ "RandomGenerator", "class_random_generator.html", "class_random_generator" ],
    [ "RRcalculator", "class_r_rcalculator.html", "class_r_rcalculator" ],
    [ "rrPlot", "classrr_plot.html", "classrr_plot" ],
    [ "SimpleHeart", "class_simple_heart.html", "class_simple_heart" ],
    [ "TimePlot", "class_time_plot.html", "class_time_plot" ],
    [ "TimestepNode", "struct_timestep_node.html", "struct_timestep_node" ],
    [ "TimeTree", "struct_time_tree.html", "struct_time_tree" ],
    [ "tVector3", "structt_vector3.html", "structt_vector3" ],
    [ "v3model", "classv3model.html", "classv3model" ],
    [ "vanDerGru", "classvan_der_gru.html", "classvan_der_gru" ]
];